# @title: 	fr make file
# @created:	2010-06-18
# @author:	effus
fr: shtrih-mini-fr-k.c
	gcc -o shtrih-mfk.bin shtrih-mini-fr-k.c -lm

printer: printer.c
	gcc -o printer.bin printer.c -lm

clean:	
	rm -rf *.bin
